name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Android_arm64-v8a-Release",
            os: ubuntu-latest,
            cmake_opts: "-DANDRIOD_ABI=arm64-v8a \
            -DANDROID_PLATFORM=25 \
            -DCMAKE_TOOLCHAIN_FILE=/usr/local/lib/android/sdk/ndk/26.3.11579264/build/cmake/android.toolchain.cmake \
            -DALSOFT_EMBED_HRTF_DATA=TRUE \
            -DALSOFT_REQUIRE_OPENSL=ON",
            build_type: "Release"
          }
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ ! -z "${{matrix.config.deps_cmdline}}" ]]; then
          eval ${{matrix.config.deps_cmdline}}
        fi
        echo 0 "/usr/local/lib/android/sdk/ndk/26.3.11579264/build/cmake/android.toolchain.cmake"
        echo 2 "ANDROID_NDK_HOME=${{$ANDROID_NDK_HOME}}"
        echo 3 "ANDROID_NDK_HOME=${{ANDROID_NDK_HOME}}"
        echo 6 "ANDROID_NDK_HOME=${{$ANDROID_NDK_PATH}}"
        echo 7 "ANDROID_NDK_HOME=${{ANDROID_NDK_PATH}}"

    - name: Configure
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} ${{matrix.config.cmake_opts}} .

    - name: Build
      shell: bash
      run: |
        cmake --build build --config ${{matrix.config.build_type}}

    - name: Test
      shell: bash
      run: |
        cd build
        ctest

    - name: Set up Windows artifacts
      if: ${{ contains(matrix.config.name, 'Win') }}
      shell: bash
      run: |
        cd build
        mkdir archive
        mkdir archive/router
        cp ${{matrix.config.build_type}}/soft_oal.dll archive
        cp ${{matrix.config.build_type}}/OpenAL32.dll archive/router

    - name: Set up Android artifacts
      if: ${{ contains(matrix.config.name, 'Android') }}
      shell: bash
      run: |
        cd build
        mkdir archive
        cp ${{github.workspace}}/build/libopenal.so archive/

    - name: Upload build as a workflow artifact
      uses: actions/upload-artifact@v4
      if: ${{ contains(matrix.config.name, 'Win') || contains(matrix.config.name, 'Android') }}
      with:
        name: soft_oal-${{matrix.config.name}}
        path: build/archive
