name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Win32-Release",
            os: windows-latest,
            cmake_opts: "-A Win32 \
              -DALSOFT_TESTS=ON \
              -DALSOFT_BUILD_ROUTER=ON \
              -DALSOFT_REQUIRE_WINMM=ON \
              -DALSOFT_REQUIRE_DSOUND=ON \
              -DALSOFT_REQUIRE_WASAPI=ON",
            build_type: "Release"
          }
        - {
            name: "Win32-Debug",
            os: windows-latest,
            cmake_opts: "-A Win32 \
              -DALSOFT_TESTS=ON \
              -DALSOFT_BUILD_ROUTER=ON \
              -DALSOFT_REQUIRE_WINMM=ON \
              -DALSOFT_REQUIRE_DSOUND=ON \
              -DALSOFT_REQUIRE_WASAPI=ON",
            build_type: "Debug"
          }
        - {
            name: "Win64-Release",
            os: windows-latest,
            cmake_opts: "-A x64 \
              -DALSOFT_TESTS=ON \
              -DALSOFT_BUILD_ROUTER=ON \
              -DALSOFT_REQUIRE_WINMM=ON \
              -DALSOFT_REQUIRE_DSOUND=ON \
              -DALSOFT_REQUIRE_WASAPI=ON",
            build_type: "Release"
          }
        - {
            name: "Win64-Debug",
            os: windows-latest,
            cmake_opts: "-A x64 \
              -DALSOFT_TESTS=ON \
              -DALSOFT_BUILD_ROUTER=ON \
              -DALSOFT_REQUIRE_WINMM=ON \
              -DALSOFT_REQUIRE_DSOUND=ON \
              -DALSOFT_REQUIRE_WASAPI=ON",
            build_type: "Debug"
          }
        - {
            name: "Win64-UWP",
            os: windows-latest,
            cmake_opts: "-A x64 \
              -DALSOFT_TESTS=OFF \
              -DCMAKE_SYSTEM_NAME=WindowsStore \
              \"-DCMAKE_SYSTEM_VERSION=10.0\" \
              -DALSOFT_BUILD_ROUTER=ON \
              -DALSOFT_REQUIRE_WASAPI=ON",
            build_type: "Release"
          }
        - {
            name: "macOS-Release",
            os: macos-latest,
            cmake_opts: "-DALSOFT_REQUIRE_COREAUDIO=ON \
              -DALSOFT_TESTS=ON",
            build_type: "Release"
          }
        - {
            name: "iOS-Release",
            os: macos-latest,
            cmake_opts: "-GXcode \
            -DCMAKE_SYSTEM_NAME=iOS \
            -DALSOFT_REQUIRE_COREAUDIO=ON \
            -DALSOFT_UTILS=OFF \
            -DALSOFT_EXAMPLES=OFF \
            -DALSOFT_TESTS=OFF \
            -DALSOFT_INSTALL=OFF \
            \"-DCMAKE_OSX_ARCHITECTURES=arm64\"",
            build_type: "Release"
          }
        - {
            name: "Linux-Release",
            os: ubuntu-latest,
            cmake_opts: "-DALSOFT_REQUIRE_RTKIT=ON \
              -DALSOFT_REQUIRE_ALSA=ON \
              -DALSOFT_REQUIRE_OSS=ON \
              -DALSOFT_REQUIRE_PORTAUDIO=ON \
              -DALSOFT_REQUIRE_PULSEAUDIO=ON \
              -DALSOFT_REQUIRE_JACK=ON \
              -DALSOFT_REQUIRE_PIPEWIRE=ON \
              -DALSOFT_TESTS=ON",
            deps_cmdline: "sudo apt update && sudo apt-get install -qq \
              libpulse-dev \
              portaudio19-dev \
              libasound2-dev \
              libjack-dev \
              libpipewire-0.3-dev \
              qtbase5-dev \
              libdbus-1-dev",
            build_type: "Release"
          }
        - {
            name: "Android_armeabi-v7a-Release",
            os: ubuntu-latest,
            cmake_opts: "-DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DALSOFT_EMBED_HRTF_DATA=TRUE \
            -DALSOFT_REQUIRE_OPENSL=ON",
            build_type: "Release"
          }
        - {
            name: "Android_arm64-v8a-Release",
            os: ubuntu-latest,
            cmake_opts: "-DANDRIOD_ABI=arm64-v8a \
            -DANDROID_PLATFORM=25 \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DALSOFT_EMBED_HRTF_DATA=TRUE \
            -DALSOFT_REQUIRE_OPENSL=ON",
            build_type: "Release"
          }
    steps:
    - uses: actions/checkout@v4

    - name: Install Dependencies
      shell: bash
      run: |
        if [[ ! -z "${{matrix.config.deps_cmdline}}" ]]; then
          eval ${{matrix.config.deps_cmdline}}
        fi

    - name: Configure
      shell: bash
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} ${{matrix.config.cmake_opts}} .

    - name: Build
      shell: bash
      run: |
        cmake --build build --config ${{matrix.config.build_type}}

    - name: Test
      shell: bash
      run: |
        cd build
        ctest

    - name: Set up Windows artifacts
      if: ${{ contains(matrix.config.name, 'Win') }}
      shell: bash
      run: |
        cd build
        mkdir archive
        mkdir archive/router
        cp ${{matrix.config.build_type}}/soft_oal.dll archive
        cp ${{matrix.config.build_type}}/OpenAL32.dll archive/router

    - name: Set up Android artifacts
      if: ${{ contains(matrix.config.name, 'Android') }}
      shell: bash
      run: |
        cd build
        mkdir archive
        cp ${{github.workspace}}/build/libopenal.so archive/

    - name: Upload build as a workflow artifact
      uses: actions/upload-artifact@v4
      if: ${{ contains(matrix.config.name, 'Win') || contains(matrix.config.name, 'Android') }}
      with:
        name: soft_oal-${{matrix.config.name}}
        path: build/archive
