name: CI

on: [push, pull_request]

jobs:
  build:
    name: ${{matrix.config.name}}
    runs-on: ${{matrix.config.os}}
    strategy:
      fail-fast: false
      matrix:
        config:
        - {
            name: "Android-Release",
            os: ubuntu-latest,
            cmake_opts: "-DANDROID_STL=c++_shared \
            -DCMAKE_TOOLCHAIN_FILE=build/cmake/android.toolchain.cmake \
            -DALSOFT_EMBED_HRTF_DATA=TRUE \
            -DALSOFT_REQUIRE_OPENSL=ON",
            deps_cmdline: "sudo apt update && sudo apt-get install -qq \
              libpulse-dev \
              portaudio19-dev \
              libasound2-dev \
              libjack-dev \
              libpipewire-0.3-dev \
              qtbase5-dev \
              libdbus-1-dev",
            build_type: "Release"
          }

    steps:
    - uses: actions/checkout@v3

    - name: Setup Android NDK
      uses: nttld/setup-ndk@v1.5.0
      with:
        ndk-version: r26d
#In case anyone is looking for a quick fix the problematic code is in config.h
#define SIZEOF_VOIDP 4
#on 64 bits this needs to be 8

    - shell: bash
      run: mkdir toolchains
    - name: specify NDK
      uses: tomasreyes/android-ndk-toolchain-setup@master
      with:
        api: '21'
        arch: 'arm64-v8a'
        install-location: 'toolchains'
        force: true


    - name: Install Dependencies
      shell: bash
      run: |
        if [[ ! -z "${{matrix.config.deps_cmdline}}" ]]; then
          eval ${{matrix.config.deps_cmdline}}
        fi

    - name: Configure
      shell: bash
      run: |
        cd /
        ls -R
        cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.config.build_type}} ${{matrix.config.cmake_opts}} .

    - name: Build
      shell: bash
      run: |
        cmake --build build --config ${{matrix.config.build_type}}

    - name: Test
      shell: bash
      run: |
        cd build
        ctest

    - name: Create Archive
      if: ${{ matrix.config.os == 'windows-latest' }}
      shell: bash
      run: |
        cd build
        mkdir archive
        mkdir archive/router
        cp ${{matrix.config.build_type}}/soft_oal.dll archive
        cp ${{matrix.config.build_type}}/OpenAL32.dll archive/router

    - name: Upload Archive
      # Upload package as an artifact of this workflow.
      uses: actions/upload-artifact@v3.1.2
      if: ${{ matrix.config.os == 'windows-latest' }}
      with:
        name: soft_oal-${{matrix.config.name}}
        path: build/archive
